baseURL = "https://pixcon.io/"
languageCode = "de"
defaultContentLanguage = "de"
title = "PIXCON"

enableRobotsTXT = true

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
